# Generated by Django 2.0.4 on 2018-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AddField(
            model_name='entry',
            name='air_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='arr_delay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='arr_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='cancelled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='carrier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='dep_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='dest',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='distance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='flight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='hour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='min',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='tailnum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
