# Generated by Django 2.0.4 on 2018-04-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20180430_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Flight',
        ),
    ]
