# Generated by Django 2.0.4 on 2018-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20180430_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dep_delay',
            field=models.CharField(default='', max_length=100),
        ),
    ]
